### ISSUE TITLE
Multiplicity of Options

### ISSUE THREAD

**Issue by BlackEdder** [jasonwhite/darg#2]
Is it possible to accept an option multiple times? I tried a couple of approaches, but was unable to get it to work.

**Comment by jasonwhite** [comment]
Normally an option overrides the previous option. You can have it call a function instead to accumulate the arguments into an array.

For example:

```d
import std.stdio;
import darg;

struct Options
{
    string[] files;

    @Option("file", "f")
    void addFile(string f) pure
    {
        files ~= f;
    }
}

int main(string[] args)
{
    auto options = parseArgs!Options(args[1..$]);

    foreach (f; options.files)
    {
        writeln(f);
    }

    return 0;
}
```

Output:
```
$ ./test --file foo.txt -f bar.txt -f baz.txt
foo.txt
bar.txt
baz.txt
```

**Comment by BlackEdder** [comment]
Thank you for the example. Might be worth it to add something to the README maybe? For example I was not aware that you could have such a function. Although thinking about it that does make sense.
